
services:
  # Serviço 1: Frontend (App Web)
  web_app:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: compose-web-lab6
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db_cache
    depends_on:
      - db_cache

  db_cache:
    image: redis:alpine
    container_name: compose-redis-lab6
    volumes:
      - redis_data_lab6:/data

volumes:
  redis_data_lab6:
    driver: local